import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="flex justify-center items-center w-screen h-screen bg-gradient-to-br from-blue-200 to-purple-400 ">
            <div className="flex flex-col bg-gray-200 rounded-2xl px-4 py-5 sm:px-10 sm:py-6 lg:px-12 text-sm sm:taxt-base h-5/6 w-10/12 sm:w-2/3 md:w-3/5 lg:w-2/5 xl:w-1/3 shadow-xl gap-8 font-mono">
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
